remote_testnet = "https://api.kylin-testnet.eospace.io"
WALLET_NAME = "VhZNXMGZ48Ti7u84nDnyq87rv"
ACCOUNT_NAME = "dgxo1uyhoytn"
OWNER_KEY = "5K4rezbmuoDUyBUntM3PqxwutPU3rYKrNzgF4f3djQDjfXF3Q67"
ACTIVE_KEY = "5JCvLMJVR24WWvC6qD6VbLpdUMsjhiXmcrk4i7bdPfjDfNMNAeX"